# Generated by Django 5.2.4 on 2025-09-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_remove_product_promtions_remove_review_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
