# Generated by Django 5.2.4 on 2025-09-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'can cancel order')]},
        ),
    ]
