# Generated by Django 5.2.4 on 2025-09-08 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promtions',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='Store.order'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
